### ISSUE TITLE
améliorer le reporting

### ISSUE THREAD

**Issue by matmut7** [SocialGouv/kontinuous#101]
Développer un moyen d'agréger les erreurs de tous les pods en erreur (et seulement les erreurs). À utiliser :
- dans un endpoint `reporting` du webhook qui sera appelé par l'Action `deploy-via-webhook`
- dans l'Action `deploy-via-github`

Permettra un meilleur reporting des erreurs sans les diluer dans le reste des logs.

**Comment by devthejo** [comment]
une amélioration partielle a déjà été réalisée en reprenant les logs dans le step qui fail en fin de pipeline,
ce n'est pas la séparation des logs mais c'est déjà un mieux qui peut être suffisant pour la milestone stable

**Comment by revolunet** [comment]
a priori l'implémentation sentry fixe ce ticket
