### ISSUE TITLE
possibilité de désactiver la notification de déploiement

### ISSUE THREAD

**Issue by matmut7** [SocialGouv/kontinuous#106]
Possibilité de désactiver la notification de déploiement Github ainsi que le commentaire sur la PR (de `debug-manifest`).

À faire pour les Actions `deploy-via-github` (à créer) et `deploy-via-webhook` (à mettre à jour).

Cas d'usage : un pipeline qui déclenche seulement un Job.

**Comment by devthejo** [comment]
fixed by new workflows repo
