### ISSUE TITLE
[deactivate]

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#198]
> Sur MDA les jobs deactivate fail assez souvent ; je sais pas si c'est normal. J'ai l'impression que c'est pour les pr avec déploiement manuel et que comme aucun déploiement n'a été fait il tombe sur un not found

https://github.com/SocialGouv/mda/actions/runs/4133455107

**Comment by devthejo** [comment]
aucun rapport avec kontinuous
https://github.com/SocialGouv/workflows/issues/3
