### ISSUE TITLE
buildkit : vérifier compatibilité avec kube@1.25

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#207]
A tester, a priori ok

**Comment by revolunet** [comment]
`Warning: spec.template.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/buildkit]: deprecated since v1.19, non-functional in v1.25+; use the "seccompProfile" field instead`

**Comment by devthejo** [comment]
will be fixed by #241
