### ISSUE TITLE
sentry: workflows errors

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#215]
Looks like in some case the deactivate workflows fail with no error. would be nice to have this in sentry as other errors 

https://github.com/SocialGouv/secretariat/actions/runs/4242075481/jobs/7373114868

**Comment by devthejo** [comment]
it should have been reported, maybe a bug, will investigate...

**Comment by devthejo** [comment]
after hours of waiting for our sentry to load, I finally found the reporting
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/91103/events/43102367091b4adb8b56c35a9ad411c1/?project=81&statsPeriod=14d

**Comment by devthejo** [comment]
no bug for me

**Comment by revolunet** [comment]
ot thanks; strange, didnt appear in the UI at that time 🤔
