### ISSUE TITLE
feat: externalize helm charts

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#227]
Etudier l'externalisation des helm charts pour pouvoir les utiliser hors kontinuous (ex: depuis manifests) et les partager avec la communauté :

 - (app)
 - hasura
 - maildev
 - ~~metabase~~ (on doit enlever le spécifique matomo)
 - (pgweb) [hubfactory](https://artifacthub.io/packages/helm/ectobit/pgweb)
 - (oauth2-proxy) [hubfactory](https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy)
 - (redis)

Deja externaliser les charts, on les peaufinera dans le nouveau repo ?

**Comment by devthejo** [comment]
will be there ;-)
https://github.com/SocialGouv/helm-charts
