### ISSUE TITLE
pg jobs and percent in pg passwords

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#282]
Looks like drop-db and other PG scripts cannot connect to databases if password contains `%`

```
job disconnect activities on database autodevops_sre-use-new-dev-preprod-flex-db-5s79filz on xxxx.postgres.database.azure.com
job psql: error: invalid percent-encoded token: "xxxxxzsv%9>4k<xxxx"
```

**Comment by matmut7** [comment]
https://dba.stackexchange.com/questions/243219/in-postgresql-url-i-cant-use-a-password-containing-special-characters

**Comment by revolunet** [comment]
fixed in https://github.com/SocialGouv/kontinuous/pull/346
