### ISSUE TITLE
degit docker image

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#332]
Looks like this image has some perf issues :

```sh
docker run -u 0 ghcr.io/socialgouv/kontinuous/degit:v1.152.0 sh -c "degit --force SocialGouv/template#hasura-amir12 /tmp/test"
```

The Job is stuck during ~2mins while the clone itself is very fast

Image is also 1gb size, maybe optimisable

**Comment by devthejo** [comment]
The both issues are not related, #333 fix only the size.
For the stucked issue, I just found it's related to the lib and I'm currently investigating on it. It's happening when the cache doesn't exists. To reproduce on your laptop, just cleanup the `.degit` dir in your home folder and try to clone again.

**Comment by revolunet** [comment]
indeed, its slower without cache folder, around ~20s here

**Comment by devthejo** [comment]
added an issue https://github.com/tiged/tiged/issues/79#issue-1754514234

**Comment by devthejo** [comment]
here is a workaround for the stucked problem, as we don't need cache here https://github.com/SocialGouv/kontinuous/pull/335

**Comment by revolunet** [comment]
unfortunately looks like this doesnt fix it 🤔 

on a cluster or locally all the degit have a strange 2mins duration +-2s

<img width="1045" alt="Capture d’écran 2023-06-14 à 01 51 20" src="https://github.com/SocialGouv/kontinuous/assets/124937/82c1db50-8668-41b4-aadf-5d4484050f80">


<img width="521" alt="Capture d’écran 2023-06-14 à 01 44 56" src="https://github.com/SocialGouv/kontinuous/assets/124937/a1815ea7-0841-4d64-b088-faee676ccdd8">

**Comment by revolunet** [comment]
Looks like this works nicely :

```sh
➜ time docker run  -ti node:18 sh -c 'npx -y tiged -f github:socialgouv/template /data'
> cloned socialgouv/template#HEAD to /data
0,07s user 0,03s system 1% cpu 6,644 total
```

**Comment by devthejo** [comment]
OK, weird, using --disable-cache seemed to work without docker. The official node image take 1G and using npx we have to wait for downloading the lib each time, with risk to break quota or having network problems. I just added my workaround (the process.exit(0) that I suggested in the issue) and update tiged2 (my fork of tiged that was used at beginning of kontinuous, used for a similar situation of unresolved issue).
Here is the kontinuous PR https://github.com/SocialGouv/kontinuous/pull/338
Tested with image and it's working pretty well. You can test with image built by the PR: `ghcr.io/socialgouv/kontinuous/degit:fix-hotfix-tiged2`

**Comment by revolunet** [comment]
Ok, weird one ! thanks for the fix 👍 
Not sure it will be fixed at tiged level tough as it works itself, sounds like some Node+Docker event issue 🤔

**Comment by devthejo** [comment]
The behavior of tiged without docker is not correct with cache enabled but empty cache, waiting for no reason after cloned.
