### ISSUE TITLE
snapshot testing

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#334]
The samples testing are quite slow to run locally (6mins) which hurts iterations

Could we make it faster by not re-executing the CLI for each test, but using JS modules directly ?

The CLI itself could be tested separately

**Comment by devthejo** [comment]
rappel: on dev, you can `yarn test:kontinuous -t name-of-the-test` to only run the test

**Comment by revolunet** [comment]
ok will try that thanks
