### ISSUE TITLE
Creation de l'action/job `DEACTIVATE`

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/kontinuous#5]
Reste à faire:

- [ ] Vérifier que le job fonctionne bien
- [ ] Debug

**Comment by revolunet** [comment]
definition of done :
 - [ ] drop review namespace
 - [ ] can drop multiple review databases and users
 - [ ] fail silently when nothing to destroy

**Comment by devthejo** [comment]
un bug corrigé récemment à retester mais devrait fonctionner en principe

**Comment by devthejo** [comment]
tested and fully functional
