### ISSUE TITLE
doc: finaliser

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/kontinuous#59]

**Comment by devthejo** [comment]
90%

**Comment by revolunet** [comment]
[![](https://mermaid.ink/img/pako:eNp1U01z0zAQ_SsaXYkzQ49hhhNMYYZegBNWDmtrUwtLK6GPpmnpf2cdJWlNkvHB-3bf2y9Jz7L3GuVK3kcIg_j2XZGiVLoKb7_-VKRNxD4bTxz9wBAf0PqAsWk-_r03WYSShskYSqeo_jkEe0l7a_KX0omK1oqQ9KzC6CkbKr6k9tUUXTFWr89Kz5QPYAs2vXfBWIzpjFxo4y0X--07Dj62y-XyQv0AuR_wXG2hQ8tuIPIZJv_EodRszKMiQtSMd9eS-pSbyF6MlzobS8remSdUtB0g8z6joqcruXhMoyH7C3mmdrj5fmQ69hFzmgywqJsTLmT-FCRMbG_nJf5bIJ_ZgNbx77CTyZoNwo633ZwS1a8eMXNez5GBAzIbTDktd-BsZc59k6J0PJd939bbc7gtQmOwfre-Lrhpt9gN3o_inTi4BIRgL2s4MttsTf_22p0KHvOztVfNBpUL6TA6MJqfzbMiIZTMAzpUcsWmhjgqqeiFeSXwsvCzNrwxucqx4EJCyf7HjvojrpxPBrgrJ1cbsIm9uNfc1be5f6ILGYB-eX_kvPwDt_hp8A?type=png)](https://mermaid.live/edit#pako:eNp1U01z0zAQ_SsaXYkzQ49hhhNMYYZegBNWDmtrUwtLK6GPpmnpf2cdJWlNkvHB-3bf2y9Jz7L3GuVK3kcIg_j2XZGiVLoKb7_-VKRNxD4bTxz9wBAf0PqAsWk-_r03WYSShskYSqeo_jkEe0l7a_KX0omK1oqQ9KzC6CkbKr6k9tUUXTFWr89Kz5QPYAs2vXfBWIzpjFxo4y0X--07Dj62y-XyQv0AuR_wXG2hQ8tuIPIZJv_EodRszKMiQtSMd9eS-pSbyF6MlzobS8remSdUtB0g8z6joqcruXhMoyH7C3mmdrj5fmQ69hFzmgywqJsTLmT-FCRMbG_nJf5bIJ_ZgNbx77CTyZoNwo633ZwS1a8eMXNez5GBAzIbTDktd-BsZc59k6J0PJd939bbc7gtQmOwfre-Lrhpt9gN3o_inTi4BIRgL2s4MttsTf_22p0KHvOztVfNBpUL6TA6MJqfzbMiIZTMAzpUcsWmhjgqqeiFeSXwsvCzNrwxucqx4EJCyf7HjvojrpxPBrgrJ1cbsIm9uNfc1be5f6ILGYB-eX_kvPwDt_hp8A)

**Comment by devthejo** [comment]
cool :-)
je viens de rajouter quelque trucs, mais je connais pas toutes les formes qu'on peut réaliser avec mermaid, du coup ça vaudra sans doute le coup d'améliorer un peu le choix des elements

**Comment by devthejo** [comment]
https://mermaid.live/edit#pako:eNp9VNuO0zAQ_ZXIrzQV7fayLYgn0IIEL4CERLIPTjJNTJ2x8WW73cu_M0naJk1aVKmeGc8cH8-c-JmlKgO2Zrnhugi-fo8xRuuTxr378jPGTBhInVBIu-_IhQeQSoMJww8vuXCB9raojMInMTYrbfG6JLoT7rNPgsa77-y_GNDKCqfMPtxBUii1fTms0a9mDbTQIAUC1QFmFbMOt0PygN_WJ2AQHNjwj0qi1g3IbZFOOFuFTqBX3katGSReyOx-AH5W-cClhzBVpRYSjB0ke9woSYfRubT5GI3H4wvna-7SAobVkicgKcwRleNVvMpBG27EY4wIkJG_vwaqrAsNRcFcYrb11qlSPEGMu4I7mqiJ8ekKFl1TZJwGNcSp6BD5lKZgITXgbGVwCVl48j2Kvx4QLNm7K0dkkPg8LDmKDVh34RzQ1V0wFTRVZ4B4P5xD9WZBAitAlrQc2ltZZz2hQHsxcgYUOpqrfo2CKbEVSSf44ozIc_omelLupljCaw9oMw5GD7q1aeNUNd7zUjaEzmP1DbRU-15fq1BX102E-qYNhMeK1j7BCMzrtjfmsXvHguH8ejXhjr7z9ye00IoMUl4paKDUDg_DkWZlQuQlWM1TGrP7n8CPdfSBiM2eeuscmJJ2SHVXldbjo43KDYmzJm-pHqP6P5Aqtxcfns4No4593zw9qZPRYQ3eBEZJqbwLLX3BvoLbcq17yoqRjVhJxLnI6CF-jjEIYuYKKCFmazIzbrYxi_GV8rh36sceU7becGlhxLwmCcNHwYlc2Yt-yqr3la2d8RSD2vvWPPf1qz9imuNvpcpjCrls_cwe2TpcrMbz2XKymK0mi9VqOlmN2J6tJ8vb8Wy6Wr6dLue3y9vV28XriD3VCJPxbLGczybT-XwynU1vljev_wAMGWbE

**Comment by revolunet** [comment]
Pour simplifier l'accès à kontinuous, je propose de présenter la feature "webhook" dans une section dédiée; 
ca permettrait de présenter une version plus simple à base de deploy classique avec `KUBECONFIG` par défaut

**Comment by revolunet** [comment]
une tentative ici : https://github.com/SocialGouv/kontinuous/pull/112
