### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#77]
See what tests we could add

Component | tests | status
------------|--------------|----
build | test manifests generation (templating) : snapshots | [to complete](https://github.com/SocialGouv/kontinuous/blob/master/.github/workflows/tests-build.yml)
deploy | e2e tests in kind ? | [to complete](https://github.com/SocialGouv/kontinuous/blob/master/.github/workflows/tests-deploy.yaml)
webhook | test deploy and security
boilerplates | ?
cli | build and commands

ideas : 
 - use projects configs for testing templating
 - tests envs related to local deployment ?

**Comment by devthejo** [comment]
> - use projects configs for testing templating
domifa has been integrated
https://github.com/SocialGouv/kontinuous/tree/master/packages/kontinuous/tests/samples/repo.domifa
https://github.com/SocialGouv/kontinuous/blob/master/packages/kontinuous/tests/__snapshots__/repo.domifa.dev.yaml
https://github.com/SocialGouv/kontinuous/blob/master/packages/kontinuous/tests/__snapshots__/repo.domifa.preprod.yaml
https://github.com/SocialGouv/kontinuous/blob/master/packages/kontinuous/tests/__snapshots__/repo.domifa.prod.yaml
```sh
yarn test:kontinuous -t repo.domifa
```

update snapshots (it's jest ;))
```sh
yarn test:kontinuous -t repo.domifa -u
```

**Comment by revolunet** [comment]
- ajouter des TUs sur debug-manifests pour pouvoir le faire évoluer
