### ISSUE TITLE
config: pouvoir activer/désactiver des plugins en fonction de l'env

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#89]
par exemple en local je ne veux pas tout ce qui concerne sealed-secrets

**Comment by devthejo** [comment]
plusieurs possibilités:
- rajouter des conditions en fonction de l'env dans les plugins (cela peut même être optionnalisable, ex un paramètre qui dit onEnvs: ["dev"] sur les options du plugin lui même)
- rajouter un hook de config custom en js (nouveau type de plugin de config)
- rajouter une clé `ifEnv` dans la config des plugins au même niveau que `enabled` et `options` (je vais déjà implémenter cette idée pour voir, moins flexible que la deuxième, mais plus générique que la première, qui est déjà possible et implémentée, ex, le plugin d'optimisation des ressources de dev, ne tourne qu'en dev, sinon il skip, c'est le cas de pas mal de plugins qui n'ont, par nature, vocation qu'à être utilisé dans un environnement spécifique)
